spring:
  application:
    name: config-server

#  profiles:
#    active: native

  cloud:
    config:
      server:
        git:
          uri: https://github.com/leandrocgsi/erudio-config-server.git
          default-label: main
          search-paths:
            - "greeting-service*"

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'